openapi: 3.0.1
info:
  title: /
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /products/{id}:
    get:
      summary: A resource for catalog Item
      operationId: getProductsId
      parameters:
      - name: id
        in: path
        description: the input string id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: NotFound
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
    patch:
      operationId: patchProductsId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "202":
          description: Accepted
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /products:
    get:
      operationId: getProducts
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: postProducts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: Created
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Product:
      required:
      - color
      - description
      - id
      - includes
      - intendedFor
      - material
      - price
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        includes:
          type: string
        intendedFor:
          type: string
        color:
          type: string
        material:
          type: string
        price:
          type: number
          format: float
